import os
import shutil
import subprocess
import sys
from skimage.metrics import structural_similarity as ssim
import cv2
import time

def compare_images_ssim(path1, path2):
    # טעינת התמונות בפורמט אפור (השוואת פיקסלים ללא השפעת צבע)
    img1 = cv2.imread(path1, cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread(path2, cv2.IMREAD_GRAYSCALE)
    if img1.shape != img2.shape:
        print(f"Resizing images: {img1.shape} -> {img2.shape}")
        img1 = cv2.resize(img1, (img2.shape, img2.shape))
    # בדיקה שהתמונות נטענו בהצלחה
    if img1 is None or img2 is None:
        print("Error: Could not load one of the images.")
        return

    # חישוב מדד ה-SSIM (התוצאה בין 0 ל-1, כאשר 1 זהות מוחלטת)
    score, _ = ssim(img1, img2, full=True)

    print(f"Similarity Score: {score:.4f}")

    if score > 0.99:  # סף של 0.99 מאפשר הבדלים זעירים ברינדור
        return True
    else:
        print(f"score is {score}")
        return False

# --- ANSI Escape Codes for Colored Terminal Output ---
RED = "\033[91m"
GREEN = "\033[92m"
RESET = "\033[0m"


def compare_file_contents(file1, file2):
    """
    Compares the content of two files line by line.
    Returns True if identical, False otherwise.
    """
    if not os.path.exists(file1) and not os.path.exists(file2):
        return True  # Both are missing, treating as match
    if not os.path.exists(file1) or not os.path.exists(file2):
        return False  # One exists and the other doesn't

    with open(file1, "r", errors="ignore") as f1, open(
        file2, "r", errors="ignore"
    ) as f2:
        return f1.read().strip() == f2.read().strip()


def run_from_terminal(test_number, name, log_file):
    # --- Define Paths ---
    exe_path = r"C:\Users\Ariel\Pythonworks\pythonhw3\HW3_26.exe"
    python_script = r"C:\Users\Ariel\Pythonworks\pythonhw3\pythonhw3.py"

    # Define the base directory where test folders will be saved
    base_test_dir = r"C:\Users\Ariel\Pythonworks\pythonhw3\tests"
    test_folder_path = os.path.join(base_test_dir, f"Test_{test_number}")

    # Create the test directory if it doesn't exist
    os.makedirs(test_folder_path, exist_ok=True)

    # --- Combine inputs into a single newline-separated string ---
    # Mimics the command line pipe input behavior
    input_feed = f"\n{name}\n{log_file}\n"

    print(
        f"\n==================== STARTING TEST #{test_number} ====================")
    print("=" * 62)

    # The exact target filenames generated by the scripts
    artifacts = [
        "factory_report.txt",
        "efficiency_chart.png"
    ]

    # --- 1. Execute the Official EXE ---
    print("[RUNNING SIMULATION 1/2] running EXE...")
    print("-" * 62)
    subprocess.run(
        [exe_path],
        input=input_feed,
        capture_output=True,
        text=True,
        errors="ignore",
    )
    time.sleep(3)

    # Move and rename EXE output files to the designated Test folder (if they exist)
    for file_name in artifacts:
        if os.path.exists(file_name):
            name_part, ext = os.path.splitext(file_name)
            dest_name = f"{name_part}_from_exe{ext}"
            shutil.move(file_name, os.path.join(test_folder_path, dest_name))

    # --- 2. Execute Your Python Script ---
    print("[RUNNING SIMULATION 2/2] Your Python Homework Script...")
    print("-" * 62)
    subprocess.run(
        [sys.executable, python_script],
        input=input_feed,
        capture_output=True,
        text=True,
        errors="ignore",
    )

    # Move and rename Python output files to the designated Test folder (if they exist)
    for file_name in artifacts:
        if os.path.exists(file_name):
            name_part, ext = os.path.splitext(file_name)
            dest_name = f"{name_part}_from_code{ext}"
            shutil.move(file_name, os.path.join(test_folder_path, dest_name))

    # --- 3. Compare Generated Artifacts Side-by-Side ---
    print(f"\n--- Artifact Comparison Results for Test #{test_number} ---")
    print("-" * 62)

    all_files_match = True

    for file_name in artifacts:
        print(f"starting {file_name}")
        name_part, ext = os.path.splitext(file_name)
        exe_file = os.path.join(test_folder_path, f"{name_part}_from_exe{ext}")
        code_file = os.path.join(test_folder_path, f"{name_part}_from_code{ext}")

        # Execute comparison check
        if "png" in exe_file or "png" in code_file:
            if compare_images_ssim(exe_file,code_file):
                print(f"{GREEN}SUCCESS:{RESET} The images are visually identical.")
            else:
                print(f"{RED}FAILED:{RESET} The images are significantly different.")
        else:
            if compare_file_contents(exe_file, code_file):
                print(f" {GREEN}[SUCCESS]{RESET} '{file_name}' matches perfectly!")
            else:
                all_files_match = False
                print(
                    f" {RED}[FAILURE]{RESET} '{file_name}' contains mismatches or is missing!"
                )

    print("-" * 62)
    if all_files_match:
        print(
            f"{GREEN}TOTAL TEST #{test_number} RESULT: PASSED! Everything is identical. 🚀{RESET}"
        )
    else:
        print(
            f"{RED}TOTAL TEST #{test_number} RESULT: FAILED! Discrepancies detected. ❌{RESET}"
        )
    print("=" * 62)

run_from_terminal(1,"ariel","factory_log.txt")